### PR TITLE
sort & compare fix AND the "lambda" example is now work perfectly )

### PR DESCRIPTION
**Pull request by SergMicar**

### CODE REVIEW

**Comment by SergMicar** [comment]
sort & compare fix

**Comment by SergMicar** [comment]
sort & compare fix

**Comment by SergMicar** [comment]
sort & compare fix

**Comment by SergMicar** [comment]
The "lambda" example is now work perfectly )

**Comment by SergMicar** [comment]
The "lambda" example is now work perfectly )

**Comment by SergMicar** [comment]
Extends "lambda"

**Comment by Anna-122** [comment]
all done

**Pull request closed without merging**
